---
abstract: "A wrapper around PAYMILL's payment API"
author:
  - 'Matthias Dietrich <perl@rainboxx.de>'
build_requires:
  Data::Compare: 0
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.014
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.0, Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Paymill-REST
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  HTTP::Request: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Module::Find: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Types::DateTime::ButMaintained: 0
  MooseX::Types::Email: 0
  MooseX::Types::URI: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/rainboxx/Paymill-REST/issues
  homepage: https://github.com/rainboxx/Paymill-REST
  repository: https://github.com/rainboxx/Paymill-REST.git
version: 0.01
x_contributors:
  - 'Matthias Dietrich <perl@rb.ly>'
